// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var DataFetcher$ReasonSsr = require("./DataFetcher.bs.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, DataFetcher$ReasonSsr.make(/* array */[])), "react-root");

console.log("hello browser");

/*  Not a pure module */
