// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Caml_option = require("bs-platform/lib/js/caml_option.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var IndexJs = require("react-dropdown/dist/index.js");

function make(className, options, onChange, _children) {
  var tmp = {
    options: options
  };
  if (className !== undefined) {
    tmp.className = Caml_option.valFromOption(className);
  }
  if (onChange !== undefined) {
    tmp.onChange = Caml_option.valFromOption(onChange);
  }
  return ReasonReact.wrapJsForReason(IndexJs.default, tmp, _children);
}

exports.make = make;
/* ReasonReact Not a pure module */
